### ISSUE TITLE
OSError: [Errno 28] inotify watch limit reached

### ISSUE THREAD

**Issue by xiaoxiaowu99** [iioSnail/csc_tools#1]
问题已经解决，感谢大佬提供开源学习code

**Comment by xiaoxiaowu99** [comment]
大佬，请教一下，又出现chineesbert报错找不到路径，这个是什么原因呀？
![image](https://github.com/iioSnail/csc_tools/assets/45588558/70d42af3-aaef-4975-b1fb-1b40499d6fb3)

**Comment by iioSnail** [comment]
模型是否正确下载了。检查下模型路径

**Comment by xiaoxiaowu99** [comment]
> 模型是否正确下载了。检查下模型路径

感谢您的回复，我是手动下载的您的模型，但是总是报找不到路径，好奇怪哦~

**Comment by xiaoxiaowu99** [comment]
> 模型是否正确下载了。检查下模型路径

大佬，关注了您的CSDN太牛掰了吧，大神级人物

**Comment by xiaoxiaowu99** [comment]
您好 十分抱歉再次打扰您，上午的错误解决了，但是总是报错Tokenizer class ChineseBertTokenizer does not exist or is not currently imported.
请问一下这个错误是否有解决方案呢？

**Comment by xiaoxiaowu99** [comment]
还有就是如果改变加载方式可以正常加载出来代码：
![image](https://github.com/iioSnail/csc_tools/assets/45588558/6cf3f12f-7399-404f-bd31-95f09fd19d64)
d但是会出现乱码的情况，求指导

**Comment by iioSnail** [comment]
刚更新了代码，对路径问题进行了修复（transformers新版本问题），可以pull下代码试试

**Comment by iioSnail** [comment]
此外，还增加了colab版本，可以先用Google colab部署试试

**Comment by xiaoxiaowu99** [comment]
谢谢大佬，非常感谢您的耐心回复，我用transformer4.12.5会出现找不到ChineseBertTokenizer的情况，
![image](https://github.com/iioSnail/csc_tools/assets/45588558/53b37a54-8baa-4481-845a-d8badf153b0a)
十分感谢您的回复~谢谢
